# ================================
# DigitalOcean App Platform Configuration
# TheModernEA Website Deployment
# ================================

name: themodernea-website
region: nyc

services:
  - name: web
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/TheModernEAWebsite
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: |
      npm ci --production=false
      npm run build
    
    # Runtime configuration
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 3000
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_URL
        value: "file:./production.db"
      - key: PORT
        value: "3000"
    
    # Resource limits
    alerts:
      - rule: CPU_UTILIZATION
        value: 85
      - rule: MEM_UTILIZATION
        value: 85

# Domain configuration for themodernea.net
domains:
  - name: themodernea.net
    type: PRIMARY
    wildcard: false
  - name: www.themodernea.net
    type: ALIAS
    wildcard: false

# Database (using SQLite for simplicity, can upgrade to managed PostgreSQL later)
databases: []

# Static assets (Next.js handles this internally)
static_sites: []

# Worker services (none needed for this app)
workers: []

# Cron jobs (none needed initially)
jobs: []